/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-04 10:49:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.hospital;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.petner.hotel.model.vo.Hotel;
import java.util.ArrayList;
import com.kh.petner.member.model.vo.Member;

public final class hospital_005fhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/hospital/../common/header.jsp", Long.valueOf(1580803751073L));
    _jspx_dependants.put("/views/hospital/../common/footer.jsp", Long.valueOf(1580549108000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.petner.member.model.vo.Member");
    _jspx_imports_classes.add("com.kh.petner.hotel.model.vo.Hotel");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 ArrayList<Hotel> list = (ArrayList)request.getAttribute("list"); 
      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("   <!-- Mobile Specific Meta -->\r\n");
      out.write("   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("   <!-- Author Meta -->\r\n");
      out.write("   <meta name=\"author\" content=\"colorlib\">\r\n");
      out.write("   <!-- Favicon-->\r\n");
      out.write("   <link rel=\"shortcut icon\" href=\"/PETNER/resources/img/common/small_logo.jpg\">\r\n");
      out.write("   <!-- meta character set -->\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <!-- Site Title -->\r\n");
      out.write("   <title>Petner+</title>\r\n");
      out.write("\r\n");
      out.write("   <link href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\" rel=\"stylesheet\">\r\n");
      out.write("   <!--\r\n");
      out.write("         CSS\r\n");
      out.write("         ============================================= -->\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/main.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("      \r\n");
      out.write("    .overlay {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        bottom: 0; }\r\n");
      out.write("\r\n");
      out.write("    .blog-banner-area {\r\n");
      out.write("        background: url(/PETNER/resources/img/hotel/dogbath.jpg) no-repeat center fixed !important; \r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        min-height:500px;\r\n");
      out.write("        }\r\n");
      out.write("  .blog-banner-area .banner-content h1 {\r\n");
      out.write("    font-size: 48px;\r\n");
      out.write("    line-height: 54px !important;\r\n");
      out.write("    margin: 0; }\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("      .blog-banner-area .banner-content h1 {\r\n");
      out.write("        font-size: 35px;\r\n");
      out.write("        line-height: 40px !important; } }\r\n");
      out.write("    @media (max-width: 414px) {\r\n");
      out.write("      .blog-banner-area .banner-content h1 {\r\n");
      out.write("        font-size: 30px; } }\r\n");
      out.write("  .blog-banner-area .banner-content p {\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    margin: 40px 20px; }\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("      .blog-banner-area .banner-content p {\r\n");
      out.write("        margin: 10px; } }\r\n");
      out.write("  .blog-banner-area .banner-content .primary-btn {\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    color: #222222; }\r\n");
      out.write("    .blog-banner-area .banner-content .primary-btn:hover {\r\n");
      out.write("      background: #3face4;\r\n");
      out.write("      color: #ffffff; }\r\n");
      out.write("\r\n");
      out.write("    .fullscreen {\r\n");
      out.write("    height: 740px; }\r\n");
      out.write("    @media (max-width: 767.98px) {\r\n");
      out.write("        .fullscreen {\r\n");
      out.write("        height: 600px !important; } }\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .fullscreen {\r\n");
      out.write("        height: 400px !important; } }\r\n");
      out.write("\r\n");
      out.write("    .overlay-bg {\r\n");
      out.write("    background-color: rgba(34, 34, 34, 0.27); }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	 Member m = (Member)session.getAttribute("member"); 

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\t\t\t<link href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\" rel=\"stylesheet\">\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css\">\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/PETNER/resources/css/font-awesome.min.css\">\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/PETNER/resources/css/bootstrap.css\" type=\"text/css\">\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/PETNER/resources/css/main.css\" type=\"text/css\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<script src=\"/PETNER/resources/js/vendor/jquery-3.4.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t\t<script src=\"/PETNER/resources/js/vendor/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t<style>\n");
      out.write("\t\t\t\t.nav-menu>li>a {\n");
      out.write("\t\t\t\t     padding-top: 30px;\n");
      out.write("\t\t\t\t     padding-bottom: 20px;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<!--################ Start Header Area ########-->\n");
      out.write("\t<header id=\"header\" class=\"fixed-top\" >\n");
      out.write("\t\t<div class=\"header-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-sm-6 col-4 no-padding\">\n");
      out.write("\t\t\t\t\t\t<div class=\"header-top-left\"  style=\"border-right: none;\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t02-777-7777\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-sm-6 col-8 header-top-right no-padding\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 if( m == null) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t<ul style=\"border-right: none;\" id=\"guest\">\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t| &nbsp;&nbsp; <a href='#' data-target=\"#modal-login\" data-toggle=\"modal\">login</a> \n");
      out.write("\t\t\t\t\t\t\t\t| <a style=\"padding-left:10px;\" href=\"/PETNER/views/member/insertMemberForm.jsp\"> Join</a>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<!--  로그인시에는 밑에 화면이 보임 -->\n");
      out.write("\t\t\t\t\t\t<ul style=\"border-right: none;\" id=\"loginMem\">\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if( m != null && m.getUserRoles() == 777) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Admin Page</a> \n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t| \t&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='#' >MyPage</a> \n");
      out.write("\t\t\t\t\t\t\t\t| \t<a style=\"padding-left:10px;\" href=\"Plogout.me\"> LogOut</a>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t<div class=\"container main-menu\">\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\" >\n");
      out.write("\t\t\t\t<div id=\"logo\">\n");
      out.write("\t\t\t\t\t<a href=\"/PETNER/index.jsp\"><img style=\"width: 100px;\" src=\"/PETNER/resources/img/common/petner_logo.jpg\" alt=\"\" title=\"\" /></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\" >\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/index.jsp\" \">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/views/etc/about.jsp\">ABOUT</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/hotelDbServlet\">HOTEL</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/views/hospital/hospital_home.jsp\">HOSPITAL</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/views/beauty/beauty_home.jsp\">BEAUTY</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"/PETNER/views/board/notice.jsp\">NOTICE</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/PETNER/views/board/notice.jsp\">NOTICE</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/PETNER/views/board/petner_faq.jsp\">FAQ</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/PETNER/views/board/qna.jsp\">Q&A</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!--######## #nav-menu-container -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!--######## End Header Area ########-->\n");
      out.write("\t\n");
      out.write("\t<!-- 로그인 모달 -->\n");
      out.write("\t\t<div class=\"row\" style=\"position: relative; vertical-align: middle;\">\n");
      out.write("\t\t\t<div class=\"modal\" id=\"modal-login\" tabindex=\"-1\">\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\" style=\"vertical-align: middle;\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t\t  <div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"text-center \">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h1 class=\"h4 text-gray-900 mb-4\">LOGIN</h1>\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\" style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form class=\"user\" id=\"loginForm\" method=\"post\" action=\"/PETNER/Plogin.me\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <input type=\"email\" class=\"form-control form-control-user\" name=\"userEmail\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  aria-describedby=\"emailHelp\" placeholder=\"이메일을 입력해주세요.\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <input type=\"password\" class=\"form-control form-control-user\" name=\"userPwd\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  placeholder=\"비밀번호를 입력해주세요.\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <div class=\"custom-control custom-checkbox small\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"customCheck\">이메일 저장</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"Plogin();\"  class=\"btn btn-primary btn-user btn-block\" style=\"background:#008000\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  Login\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <!-- 비번 찾기랑 회원가입하기버튼 수정해야함  -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 일단은 안보이게해놈 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <a href=\"forgot-password.html\" style=\"padding-right: 20px;\">비밀번호 찾기</a>  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"register.html\" style=\"padding-left: 20px;\">회원가입</a> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modal-login\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t    <div class=\"modal-content\">\n");
      out.write("\t\t      <div class=\"modal-header\">\n");
      out.write("\t\t        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Modal title</h5>\n");
      out.write("\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t        </button>\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t      <div class=\"modal-body\">\n");
      out.write("\t\t        ...\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t      <div class=\"modal-footer\">\n");
      out.write("\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("\t\t        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\t//로그인 서블릿으로 보내는 함수\n");
      out.write("\t\tfunction Plogin(){\t\n");
      out.write("\t\t\t$('#loginForm').submit();\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("      <!--######## start banner Area ########-->\r\n");
      out.write("      <!--  메뉴바랑 겹치는 부분 제거 -->\r\n");
      out.write("      <div style=\"padding-top:150px;\"></div>\r\n");
      out.write("      \r\n");
      out.write("   <!--######## Start Header Area ########-->\r\n");
      out.write("\r\n");
      out.write("   <!--######## End Header Area ########-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!--######## start banner Area ########-->\r\n");
      out.write("   <section class=\"blog-banner-area relative\" id=\"home\">\r\n");
      out.write("      <div class=\"overlay overlay-bg\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row text-left d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"about-content col-lg-12\">\r\n");
      out.write("               <h1 class=\"text-white text-uppercase  \">\r\n");
      out.write("                  HOTEL\r\n");
      out.write("               </h1>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   <!--######## End banner Area ########-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Start CheckBox -->\r\n");
      out.write("   <section class=\"whole-wrap\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("         <div class=\"section-top-border\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("               <div class=\"col-lg-12 col-md-12\">\r\n");
      out.write("                  <h3 class=\"mb-30\">지역찾기</h3>\r\n");
      out.write("                  <div class=\"checkbox-background\">\r\n");
      out.write("                     <br>&nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"checkbox\" id=\"gangnam\">\r\n");
      out.write("                     <label for=\"gangnam\">강남,송파,서초</label>\r\n");
      out.write("                     &nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"checkbox\" id=\"gangseo\">\r\n");
      out.write("                     <label for=\"gangseo\">영등포,강서</label>\r\n");
      out.write("                     &nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"checkbox\" id=\"hongdae\">\r\n");
      out.write("                     <label for=\"hongdae\">홍대,용산,종로</label>\r\n");
      out.write("                     &nbsp;&nbsp;\r\n");
      out.write("                     <input type=\"checkbox\" id=\"other\">\r\n");
      out.write("                     <label for=\"other\">기타</label>\r\n");
      out.write("                     <br>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-6 col-md-6 marg30\">\r\n");
      out.write("                  <div class=\"search-div\">\r\n");
      out.write("                     <input type=\"text\" class=\"search-input\" placeholder=\"검색어를 입력하세요.\">\r\n");
      out.write("                     <button class=\"search-btn\">검색</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-lg-6 col-md-6 marg45 \">\r\n");
      out.write("                  <div class=\"recent-completed-project1\">\r\n");
      out.write("                     <div class=\"filters project-filter\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                           <li class=\"active\" data-filter=\".new\">최근등록순</li>|\r\n");
      out.write("                           <li data-filter=\".grade\">평점순</li>| \r\n");
      out.write("                           <li data-filter=\".review\">후기순</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"col-md-12 col\">\r\n");
      out.write("                  <hr>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   <!-- End checkBox -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!--######## Start Latest News Area ########-->\r\n");
      out.write("   <section class=\"latest-news-area section-gap-hr\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         ");
 for(Hotel h : list) { 
      out.write("\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("               <div class=\"single-newss card\">\r\n");
      out.write("                  <img class=\"card-top-img \" height=\"400px\" src=\"/PETNER/resources/img/hotel/hop_img2.jpeg\" alt=\"hospital image\">\r\n");
      out.write("                  <div class=\"card-body\">\r\n");
      out.write("                     <h4 class=\"card-title\">\r\n");
      out.write("                        <a href=\"hotel_information.html\">\r\n");
      out.write("                           ");
      out.print(h.getHotel_name());
      out.write("\r\n");
      out.write("                          \r\n");
      out.write("                           \r\n");
      out.write("                        </a>\r\n");
      out.write("                     </h4>\r\n");
      out.write("                     <i class=\"fa fa-star star\"></i><i class=\"fa fa-star star\"></i><i class=\"fa fa-star star\"></i><i class=\"fa fa-star star\" star></i><i\r\n");
      out.write("                        class=\"fa fa-star star\"></i>\r\n");
      out.write("                        <span>&nbsp&nbsp후기 132개</span>\r\n");
      out.write("                     <p class=\"card-text\">\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <img src=\"/PETNER/resources/img/hotel/pin.png\" width=\"15px\" height=\"15px\">\r\n");
      out.write("                        서울시 강남구\r\n");
      out.write("                        <br>이용시간 평일 00:00 ~ 24:00<br>\r\n");
      out.write("                        연중휴무</p>\r\n");
      out.write("                        <a href=\"hotel_information.html\" class=\"primary-btn header-btn text-capitalize mt-10\" style=\"float: right;\">예약하기</a>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("            <!-- 페이징 부분 -->\r\n");
      out.write("            <nav class=\"col-md-12 blog-pagination justify-content-center d-flex\">\r\n");
      out.write("               <ul class=\"pagination\">\r\n");
      out.write("                  <li class=\"page-item\">\r\n");
      out.write("                     <a href=\"#\" class=\"page-link\" aria-label=\"Previous\">\r\n");
      out.write("                        <span aria-hidden=\"true\">\r\n");
      out.write("                           <span class=\"lnr lnr-chevron-left\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li class=\"page-item\"><a href=\"#\" class=\"page-link\">01</a></li>\r\n");
      out.write("                  <li class=\"page-item active\"><a href=\"#\" class=\"page-link\">02</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a href=\"#\" class=\"page-link\">03</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a href=\"#\" class=\"page-link\">04</a></li>\r\n");
      out.write("                  <li class=\"page-item\"><a href=\"#\" class=\"page-link\">05</a></li>\r\n");
      out.write("                  <li class=\"page-item\">\r\n");
      out.write("                     <a href=\"#\" class=\"page-link\" aria-label=\"Next\">\r\n");
      out.write("                        <span aria-hidden=\"true\">\r\n");
      out.write("                           <span class=\"lnr lnr-chevron-right\"></span>\r\n");
      out.write("                        </span>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </li>\r\n");
      out.write("               </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </section>\r\n");
      out.write("   <!--######## End Latest News Area ########-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!--######## start footer Area ########-->\r\n");
      out.write("\r\n");
      out.write("   <!--######## End footer Area ########-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!--######## start footer Area ########-->\r\n");
      out.write("\t<footer class=\"footer-area section-gap\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"footer-bottom d-flex justify-content-between align-items-center flex-wrap\">\r\n");
      out.write("\t\t\t\t<p class=\"col-lg-8 col-sm-12 footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved<i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Petner+</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t\t<div class=\"footer-social d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!--######## End footer Area ########-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
