/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-02-06 07:13:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.petner.member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1580973177623L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1580549108000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.petner.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<!-- Mobile Specific Meta -->\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("\t<!-- Author Meta -->\n");
      out.write("\t<meta name=\"author\" content=\"colorlib\">\n");
      out.write("\t<!-- Favicon-->\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"/PETNER/resources/img/common/small_logo.jpg\">\n");
      out.write("\t<!-- meta character set -->\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<!-- Site Title -->\n");
      out.write("\t<title>Petner+</title>\n");
      out.write("</head>\n");
      out.write("<style>\n");
      out.write("\t.home-banner-area {\n");
      out.write("  background: url(/PETNER/resources/img/dogcat.jpg) no-repeat center fixed !important;\n");
      out.write("  background-size: cover; }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t");
      out.write('\n');
      out.write('\n');
      out.write('\n');

	 Member m = (Member)session.getAttribute("member"); 

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\t\t\t<link href=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\" rel=\"stylesheet\">\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.6.11/css/lightgallery.min.css\">\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/PETNER/resources/css/font-awesome.min.css\">\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/PETNER/resources/css/bootstrap.css\" type=\"text/css\">\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/PETNER/resources/css/main.css\" type=\"text/css\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<script src=\"/PETNER/resources/js/vendor/jquery-3.4.1.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t\t<script src=\"/PETNER/resources/js/vendor/bootstrap.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t<style>\n");
      out.write("\t\t\t\t.nav-menu>li>a {\n");
      out.write("\t\t\t\t     padding-top: 30px;\n");
      out.write("\t\t\t\t     padding-bottom: 20px;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t<!--################ Start Header Area ########-->\n");
      out.write("\t<header id=\"header\" class=\"fixed-top\" >\n");
      out.write("\t\t<div class=\"header-top\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-sm-6 col-4 no-padding\">\n");
      out.write("\t\t\t\t\t\t<div class=\"header-top-left\"  style=\"border-right: none;\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-phone\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t02-777-7777\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-6 col-sm-6 col-8 header-top-right no-padding\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 if( m == null) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t<ul style=\"border-right: none;\" id=\"guest\">\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t| &nbsp;&nbsp; <a href='#' data-target=\"#modal-login\" data-toggle=\"modal\">login</a> \n");
      out.write("\t\t\t\t\t\t\t\t| <a style=\"padding-left:10px;\" href=\"/PETNER/views/member/insertMemberForm.jsp\"> Join</a>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 }else{ 
      out.write("\n");
      out.write("\t\t\t\t\t\t<!--  로그인시에는 밑에 화면이 보임 -->\n");
      out.write("\t\t\t\t\t\t<ul style=\"border-right: none;\" id=\"loginMem\">\n");
      out.write("\t\t\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t\t\t\t");
 if( m != null && m.getUserRoles() == 777) { 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Admin Page</a> \n");
      out.write("\t\t\t\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t| \t&nbsp;&nbsp; \n");
      out.write("\t\t\t\t\t\t\t\t\t<a href='#' >MyPage</a> \n");
      out.write("\t\t\t\t\t\t\t\t| \t<a style=\"padding-left:10px;\" href=\"Plogout.me\"> LogOut</a>\n");
      out.write("\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t<div class=\"container main-menu\">\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\" >\n");
      out.write("\t\t\t\t<div id=\"logo\">\n");
      out.write("\t\t\t\t\t<a href=\"/PETNER/views/member/searchPwForm.jsp\"><img style=\"width: 100px;\" src=\"/PETNER/resources/img/common/petner_logo.jpg\" alt=\"\" title=\"\" /></a>\n");
      out.write("\t\t\t\t</div> <!-- sikim index  -->\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\" >\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/index.jsp\" \">Home</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/views/etc/about.jsp\">ABOUT</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/hotelDbServlet\">HOTEL</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/views/hospital/hospital_home.jsp\">HOSPITAL</a>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/PETNER/views/beauty/beauty_home.jsp\">BEAUTY</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"/PETNER/views/board/notice.jsp\">NOTICE</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/PETNER/views/board/notice.jsp\">NOTICE</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/PETNER/views/board/petner_faq.jsp\">FAQ</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/PETNER/views/board/qna.jsp\">Q&A</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!--######## #nav-menu-container -->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</header>\n");
      out.write("\t<!--######## End Header Area ########-->\n");
      out.write("\t\n");
      out.write("\t<!-- 로그인 모달 -->\n");
      out.write("\t\t<div class=\"row\" style=\"position: relative; vertical-align: middle;\">\n");
      out.write("\t\t\t<div class=\"modal\" id=\"modal-login\" tabindex=\"-1\">\n");
      out.write("\t\t\t\t<div class=\"modal-dialog\" style=\"vertical-align: middle;\">\n");
      out.write("\t\t\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t\t\t  <div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t  <div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t\t  <div class=\"text-center \">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h1 class=\"h4 text-gray-900 mb-4\">LOGIN</h1>\n");
      out.write("\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\" style=\"text-align: center;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<form class=\"user\" id=\"loginForm\" method=\"post\" action=\"/PETNER/Plogin.me\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <input type=\"email\" class=\"form-control form-control-user\" name=\"userEmail\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  aria-describedby=\"emailHelp\" placeholder=\"이메일을 입력해주세요.\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <input type=\"password\" class=\"form-control form-control-user\" name=\"userPwd\" \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  placeholder=\"비밀번호를 입력해주세요.\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <div class=\"custom-control custom-checkbox small\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"customCheck\">이메일 저장</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" onclick=\"Plogin();\"  class=\"btn btn-primary btn-user btn-block\" style=\"background:#008000\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  Login\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <hr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  <div class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <br>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t  <!-- 비번 찾기랑 회원가입하기버튼 수정해야함  -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- 일단은 안보이게해놈 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <a href=\"forgot-password.html\" style=\"padding-right: 20px;\">비밀번호 찾기</a>  \n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"register.html\" style=\"padding-left: 20px;\">회원가입</a> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"modal fade\" id=\"modal-login\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t\t    <div class=\"modal-content\">\n");
      out.write("\t\t      <div class=\"modal-header\">\n");
      out.write("\t\t        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Modal title</h5>\n");
      out.write("\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t        </button>\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t      <div class=\"modal-body\">\n");
      out.write("\t\t        ...\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t      <div class=\"modal-footer\">\n");
      out.write("\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\n");
      out.write("\t\t        <button type=\"button\" class=\"btn btn-primary\">Save changes</button>\n");
      out.write("\t\t      </div>\n");
      out.write("\t\t    </div>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\t//로그인 서블릿으로 보내는 함수\n");
      out.write("\t\tfunction Plogin(){\t\n");
      out.write("\t\t\t$('#loginForm').submit();\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
      out.write(" \n");
      out.write("\t<!--######## start banner Area ########-->\n");
      out.write("\t<!--  메뉴바랑 겹치는 부분 제거 -->\n");
      out.write("\t<div style=\"padding-top:150px;\"></div>\n");
      out.write("\t\n");
      out.write("\t<section class=\"home-banner-area relative\" id=\"home\" >\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row fullscreen d-flex align-items-center\">\n");
      out.write("\t\t\t\t<div class=\"banner-content col-lg-9 col-md-12\">\n");
      out.write("\t\t\t\t\t<h1>\n");
      out.write("\t\t\t\t\t\tPetner + <br> With <br> Your Life\n");
      out.write("\t\t\t\t\t</h1>\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"primary-btn header-btn text-capitalize mt-10\">hire us now!</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!--######## End banner Area ########-->\n");
      out.write("\n");
      out.write("\t<!--######## Start Latest News Area ########-->\n");
      out.write("\t<section class=\"latest-news-area section-gap\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t<div class=\"main-title text-center\">\n");
      out.write("\t\t\t\t\t\t<h1>Hotel</h1>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"single-news card\">\n");
      out.write("\t\t\t\t\t\t<img class=\"card-top-img\" style=\"height: 250px;\" src=\"resources/img/bath.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"text-align: center;\" class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<a style=\"font-weight: 400;\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\tBath & Spa Service\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t<p  style=\"text-align: center;\" class=\"card-text\">반려동물들의 피로감을 씻어줄 스파와 <br>목욕 서비스를 제공합니다.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"single-news card\">\n");
      out.write("\t\t\t\t\t\t<img class=\"card-top-img\" style=\"height: 250px;\" src=\"resources/img/exercise.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"text-align: center;\" class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<a style=\"font-weight: 400;\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\tA pet Kidergarten\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t<p style=\"text-align: center;\" class=\"card-text\">반려동물의 사회성을 키워주고, 다양한 놀이 <br>서비스를 제공하는 유치원을 운영합니다.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-4 col-md-6\">\n");
      out.write("\t\t\t\t\t<div class=\"single-news card\">\n");
      out.write("\t\t\t\t\t\t<img class=\"card-top-img\" style=\"height: 250px;\" src=\"resources/img/walk.jpg\" alt=\"Card image cap\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t<h4 style=\"text-align: center;\" class=\"card-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<a style=\"font-weight: 400;\" href=\"#\">\n");
      out.write("\t\t\t\t\t\t\t\t\tA walking Service\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t<p style=\"text-align: center;\" class=\"card-text\">반려동물들의 스트레스 해소를 위해<br> 산책서비스를 제공합니다.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!--######## End Latest News Area ########-->\n");
      out.write("\n");
      out.write("<hr>\n");
      out.write("\t<!--######## Start Recent Completed Project Area ########-->\n");
      out.write("\t<section class=\"recent-completed-project section-gap\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t<div class=\"main-title text-center\">\n");
      out.write("\t\t\t\t\t\t<h1>Beauty</h1>\n");
      out.write("\t\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t<div class=\"projects_inner row\" id=\"lightgallery\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-sm-6 web all\" data-src=\"resources/img/beauty1.jpg\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/beauty1.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"resources/img/icon.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_text\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 style=\"font-weight: 200;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"portfolio-details.html\">Pomeranian</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>가위컷</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-sm-6 brand all creative\" data-src=\"resources/img/beauty2.jpg\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/beauty2.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"resources/img/icon.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_text\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 style=\"font-weight: 200;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"portfolio-details.html\">Cat</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>무마취미용</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-sm-6 all\" data-src=\"resources/img/beauty3.jpg\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/beauty3.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"resources/img/icon.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_text\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 style=\"font-weight: 200;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"portfolio-details.html\">Chihuahua </a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>가위컷</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-sm-6 all print-mat\" data-src=\"resources/img/beauty4.jpg\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/beauty4.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"resources/img/icon.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_text\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 style=\"font-weight: 200;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"portfolio-details.html\">Cocker Spaniel</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>바리깡+가위컷</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-sm-6 brand img-man all\" data-src=\"resources/img/beauty5.jpg\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/beauty5.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"resources/img/icon.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_text\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 style=\"font-weight: 200;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"portfolio-details.html\">Pomeranian</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>곰돌이컷</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-4 col-sm-6 brand work img-man all\" data-src=\"resources/img/beauty6.jpg\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_item\">\n");
      out.write("\t\t\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/beauty6.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"icon\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img class=\"img-fluid\" src=\"resources/img/icon.png\" alt=\"\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"projects_text\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4 style=\"font-weight: 200;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"portfolio-details.html\">Beagle</a>\n");
      out.write("\t\t\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>바리깡</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!--######## End Recent Completed Project Area ########-->\n");
      out.write("\n");
      out.write("\t<!--######## Start testimonial Area ########-->\n");
      out.write("\t<section class=\"testimonial-area section-gap\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t<div class=\"single-testimonial item d-flex flex-row\">\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: center;\"class=\"desc\">\n");
      out.write("\t\t\t\t\t\t\t<p style=\"color: black;\">\n");
      out.write("\t\t\t\t\t\t\t\t버려진 동물 12만마리 ,\n");
      out.write("\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t<h4 mt-30>사지말고 <span style=\"font-weight: bold;\">'입양'</span> 하세요.</h4>\n");
      out.write("\t\t\t\t\t\t\t<p style=\"color: black;\" class=\"mb-0\">많은 동물들이 당신을 기다리고 있습니다.</p>\n");
      out.write("\t\t\t\t\t\t\t<p style=\"color: black;\" class=\"mb-0\">Don't buy a pet adopt one.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!--######## End testimonial Area ########-->\n");
      out.write("\n");
      out.write("\t<!--######## Start Latest Blog Area ########-->\n");
      out.write("\t<section class=\"latest-blog-area section-gap\">\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t\t\t<div class=\"main-title text-center\">\n");
      out.write("\t\t\t\t\t\t<h1>Hosipital</h1>\n");
      out.write("\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 single-blog\">\n");
      out.write("\t\t\t\t\t<div class=\"thumb\">\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/hospital2.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- <p class=\"date\">10 Jan 2018</p> -->\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<h4 style=\"font-weight:400;\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Animal Vaccination</a>\n");
      out.write("\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t각종 예방접종을 실시합니다. <br>반려동물의 건강한 삶의 질을 위한<br> 필수 과정입니다.\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<div class=\"meta-bottom d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t<!-- <p><span class=\"lnr lnr-heart\"></span> 15 Likes</p>\n");
      out.write("\t\t\t\t\t\t<p><span class=\"lnr lnr-bubble\"></span> 02 Comments</p> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 single-blog\">\n");
      out.write("\t\t\t\t\t<div class=\"thumb\">\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/hospital3.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- <p class=\"date\">10 Jan 2018</p> -->\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<h4 style=\"font-weight:400;\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Excellent Facilities</a>\n");
      out.write("\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t훌륭한 시설과 진료 기계들을 <br>보장합니다.\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<div class=\"meta-bottom d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t<!-- <p><span class=\"lnr lnr-heart\"></span> 15 Likes</p>\n");
      out.write("\t\t\t\t\t\t<p><span class=\"lnr lnr-bubble\"></span> 02 Comments</p> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 single-blog\">\n");
      out.write("\t\t\t\t\t<div class=\"thumb\">\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/hospital6.jpeg\" alt=\"\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- <p class=\"date\">10 Jan 2018</p> -->\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<h4 style=\"font-weight:400;\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">24Hours Clinic</a>\n");
      out.write("\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t야간 진료 및 24시간 운영을 지원합니다.<br>언제나 찾을 수 있습니다.\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<div class=\"meta-bottom d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t<!-- <p><span class=\"lnr lnr-heart\"></span> 15 Likes</p>\n");
      out.write("\t\t\t\t\t\t<p><span class=\"lnr lnr-bubble\"></span> 02 Comments</p> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-lg-3 col-md-6 single-blog\">\n");
      out.write("\t\t\t\t\t<div class=\"thumb\">\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid w-100\" src=\"resources/img/hospital7.jpg\" alt=\"\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- <p class=\"date\">10 Jan 2018</p> -->\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<h4 style=\"font-weight:400;\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#\">Animal Operation</a>\n");
      out.write("\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t\t믿을 수 있는 수술을 받을 수 있습니다.<br>전문 진료진들이 준비하고 있습니다.\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<div class=\"meta-bottom d-flex justify-content-between\">\n");
      out.write("\t\t\t\t\t\t<!-- <p><span class=\"lnr lnr-heart\"></span> 15 Likes</p>\n");
      out.write("\t\t\t\t\t\t<p><span class=\"lnr lnr-bubble\"></span> 02 Comments</p> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</section>\n");
      out.write("\t<!--######## End Latest Blog Area ########-->\n");
      out.write("\t\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!--######## start footer Area ########-->\r\n");
      out.write("\t<footer class=\"footer-area section-gap\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"footer-bottom d-flex justify-content-between align-items-center flex-wrap\">\r\n");
      out.write("\t\t\t\t<p class=\"col-lg-8 col-sm-12 footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved<i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> by <a href=\"https://colorlib.com\" target=\"_blank\">Petner+</a>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("</p>\r\n");
      out.write("\t\t\t\t<div class=\"footer-social d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-dribbble\"></i></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!--######## End footer Area ########-->\r\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
